const GET_SPOTS_BEJIN = 'GET_SPOTS_BEJIN';
const GET_SPOTS_SUCCESS = 'GET_SPOTS_SUCCESS';
const GET_SPOTS_ERROR = 'GET_SPOTS_ERROR';

const SORT_SPOTS = 'SORT_SPOTS';
const SET_PATH_ID = 'SET_PATH_ID';

const CLOSE_MODAL = 'CLOSE_MODAL';
const OPEN_MODAL = 'OPEN_MODAL';

const SET_SINGLE_SPOT = 'SET_SINGLE_SPOT';

export {
  GET_SPOTS_BEJIN,
  GET_SPOTS_SUCCESS,
  GET_SPOTS_ERROR,
  SORT_SPOTS,
  SET_PATH_ID,
  CLOSE_MODAL,
  OPEN_MODAL,
  SET_SINGLE_SPOT,
};
