const GET_SPOTS_BEJIN = 'GET_SPOTS_BEJIN';
const GET_SPOTS_SUCCESS = 'GET_SPOTS_SUCCESS';
const GET_SPOTS_ERROR = 'GET_SPOTS_ERROR';

const SORT_SPOTS = 'SORT_SPOTS';

export { GET_SPOTS_BEJIN, GET_SPOTS_SUCCESS, GET_SPOTS_ERROR, SORT_SPOTS };
